export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const UPDATE_CART_QUANTITY = 'UPDATE_CART_QUANTITY';
export const EMPTY_CART = 'EMPTY_CART';
export const TOGGLE_CART = 'TOGGLE_CART';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const DELETE_PRODUCT ='DELETE_PRODUCT';
